version: "3.2"
services:
  # The API service
  api:
    user: ${USER}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - PASSWD=${PASSWD}
    container_name: codepraise-api
    ports:
      - 9090:9090
    volumes:
      - ..:/home/${USER}/workspace
      - ${HOME}${USERPROFILE}/.ssh:/home/${USER}/.ssh
      - ${HOME}${USERPROFILE}/.gitconfig:/home/${USER}/.gitconfig
    working_dir: /home/${USER}/workspace
    command: sleep infinity
